name: covid19
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  material_design_icons_flutter: ^4.0.5145
  url_launcher: ^5.4.5
  carousel_slider: ^1.3.0
  flutter_vector_icons: ^0.2.1
  flutter_spinkit: ^4.1.2+1
  http: ^0.12.1
  dio: ^3.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/images/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

